services:
    db:
        container_name: mariadb
        build: ./requirements/mariadb
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        expose:
            - "3306"
        restart: unless-stopped
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        env_file: .env
        volumes:
            - wp:/var/www/html
        depends_on:
            - db
        networks:
            - inception
        expose:
            - "9000"
        restart: on-failure
    web:
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - wp:/var/www/html
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - inception
        restart: on-failure

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: "~/data/mariadb"
    wp:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: "~/data/wordpress"

networks:
    inception:
        driver: bridge