services:
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        env_file:
            - .env
        expose:
            - "3306"
        networks:
            - inception
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping --silent && mysql -u"$DB_USER" -p"$DB_PASSWD" -e "USE $DB_NAME;"
            interval: 2s
            timeout: 5s
            retries: 5
            start_period: 2s
    wordpress:
        build: requirements/wordpress
        container_name: wordpress
        env_file:
            - .env
        expose:
            - "9000"
        networks:
            - inception
        volumes:
            - wp:/var/www/html
        depends_on:
            mariadb:
                condition: service_healthy
                restart: true

    nginx:
        build: requirements/nginx
        container_name: nginx
        ports:
            - "443:443"
        networks:
            - inception
        volumes:
            - wp:/var/www/html
        depends_on:
            wordpress:
                condition: service_started
volumes:
    wp:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "~/data/wp/"
    db:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "~/data/db/"

networks:
    inception:
        driver: bridge

        