services:
    db:
        container_name: mariadb
        #networks:
        #    - inception
        build: ./requirements/mariadb
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
        expose:
            - "3306"

volumes:
    mariadb:
        driver: local